export * from './test.model';
export * from './exam.model';
export * from './car.model';
// export * from './movie.model';
// export * from './location.model';
// export * from './concessions.model';
export * from './customer.model';
export * from './employee.model';
export * from './movie.model';
export * from './room.model';
export * from './theater.model';